servera:
	gcc -std=gnu99 -Wall -o prog21a_s prog21a_s.c
serverb:
	gcc -std=gnu99 -Wall -o prog21b_s prog21b_s.c

client:
	gcc -std=gnu99 -Wall -o prog21a_c prog21a_c.c

clear:
	-rm prog21a_c prog21a_s prog21b_s
